### PR TITLE
Fix #780

### LINKED ISSUE #780: Avoid unnecessary else statements
This is just a general code-styling rule and not necessary to follow. However, it does help avoid bugs at times.

I'm using the `astra_get_foreground_color()` function from `inc/core/common-functions.php` as an example:

```php
function astra_get_foreground_color( $hex ) {

	if ( 'transparent' == $hex || 'false' == $hex || '#' == $hex || empty( $hex ) ) {
		return 'transparent';

	} else {

		// Get clean hex code.
		$hex = str_replace( '#', '', $hex );

		if ( 3 == strlen( $hex ) ) {
			$hex = str_repeat( substr( $hex, 0, 1 ), 2 ) . str_repeat( substr( $hex, 1, 1 ), 2 ) . str_repeat( substr( $hex, 2, 1 ), 2 );
		}

		// Get r, g & b codes from hex code.
		$r   = hexdec( substr( $hex, 0, 2 ) );
		$g   = hexdec( substr( $hex, 2, 2 ) );
		$b   = hexdec( substr( $hex, 4, 2 ) );
		$hex = ( ( $r * 299 ) + ( $g * 587 ) + ( $b * 114 ) ) / 1000;

		return 128 <= $hex ? '#222222' : '#ffffff';
	}
}
```

The `else` statement is unnecessary.  The could simply be written as:

```php
function astra_get_foreground_color( $hex ) {

	if ( 'transparent' == $hex || 'false' == $hex || '#' == $hex || empty( $hex ) ) {
		return 'transparent';

	}

	// Get clean hex code.
	$hex = str_replace( '#', '', $hex );

	if ( 3 == strlen( $hex ) ) {
		$hex = str_repeat( substr( $hex, 0, 1 ), 2 ) . str_repeat( substr( $hex, 1, 1 ), 2 ) . str_repeat( substr( $hex, 2, 1 ), 2 );
	}

	// Get r, g & b codes from hex code.
	$r   = hexdec( substr( $hex, 0, 2 ) );
	$g   = hexdec( substr( $hex, 2, 2 ) );
	$b   = hexdec( substr( $hex, 4, 2 ) );
	$hex = ( ( $r * 299 ) + ( $g * 587 ) + ( $b * 114 ) ) / 1000;

	return 128 <= $hex ? '#222222' : '#ffffff';
}
```

When I first looked at the code, I thought it wasn't returning anything.  It wasn't until I scrolled back up to see that there was an `else` that wrapped the `return`.  Generally speaking, `else` statements are a sign that the code can be written in a better way or shortened up to decrease complexity.

### PR DESCRIPTION
**Pull request by actual-saurabh**

### CODE REVIEW

**Comment by Nikschavan** [comment]
@actual-saurabh This PR will need a conflict resolution.

**Comment by actual-saurabh** [comment]
@Nikschavan the conflict is because by returning early and therefore, removing the else, the code that follows has changed its indentation. [See the changes](https://github.com/brainstormforce/astra/pull/884/files) for what I mean.

Am I wrong in assuming that you would be able to resolve it while merging?

**Comment by actual-saurabh** [comment]
Done, I think I created this branch from another branch instead of dev and that's why ran into the conflict with the grades tab on Student Dashboard.

There was also a CS issue with my inline comment.

Fixed, all ready for review @Nikschavan

**Comment by Nikschavan** [comment]
Thank you very much for this @actual-saurabh 👍

**Pull request merged**
