### PR TITLE
WIP: CSS optimization mega menu fixes

### PR DESCRIPTION
**Pull request by Balachandark**

### CODE REVIEW

**Comment by premanshup** [comment]
@imnavanath Can we close this PR?

**Comment by imnavanath** [comment]
> @imnavanath Can we close this PR?

Yes, @premanshup surely we can close this PR.

**Comment by premanshup** [comment]
> > @imnavanath Can we close this PR?
> 
> Yes, @premanshup surely we can close this PR.

Thank you for the confirmation.

**Comment by premanshup** [comment]
Closing this PR as this is fixed in the PR - #1758

**Pull request closed without merging**
