### PR TITLE
fix: NPM dependency updates

### PR DESCRIPTION
**Pull request by Nikschavan**
### Description
Update NPM dependencies by running `npm audit fix`

### Types of changes
- Bug fix - Update NPM dependencies - by running `npm audit fix`

### Checklist:
- [x] My code is tested
- [x] My code passes the PHPCS tests
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

### CODE REVIEW

**Review by patilvikasj — APPROVED** [review]

**Comment by Nikschavan** [comment]
@premanshup - Any idea why Semantic Pull request is still failing after I have renamed the PR title?

**Comment by premanshup** [comment]
> @premanshup - Any idea why Semantic Pull request is still failing after I have renamed the PR title?

@Nikschavan Sir, Yes, it is compulsory to have at least one commit following the semantic coding standards.

**Comment by Nikschavan** [comment]
I think we can disable the requirement of commit as this only checks for single commit and hence does not safeguard against bad commit messages altogether.

I have created PR https://github.com/brainstormforce/astra/pull/2310 to limit this only for titles, once that is merged I will update this PR as well.

**Comment by Nikschavan** [comment]
@premanshup let's get this merged.

**Review by premanshup — APPROVED** [review]

**Pull request merged**
