### PR TITLE
AST-2113 - Deprecated function warning on elementor install

### PR DESCRIPTION
**Pull request by yssambare12**
### Description
- Issue - When we set WP_DEBUG to true, then the frontend shows this warning - https://d.pr/i/hgbdHK. And when we change to the default theme, the warning is gone. We have around four-five tickets for this issue.

**Steps To Reproduce:** 

1. Install Astra theme
2. Install Elementor
3. Enable debug mode in WordPress and you will be able to see the warning 
4. Check any page on the front-end showing a deprecated warning error.

### Screenshots

- https://d.pr/i/hgbdHK

### Types of changes

**Actual Result:**

- Showing deprecated warning on frontend

**Expected Result:** 

- Error needs to be gone

### Checklist:
- [x] My code is tested
- [x] My code passes the PHPCS tests
- [x] My code follows accessibility standards 
- [x] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

### CODE REVIEW

**Comment by imnavanath** [comment]
@yssambare12 code analysis failed, please check.

**Comment by yssambare12** [comment]
> @yssambare12 code analysis failed, please check. also add changelog for this.

Ok! I will did the necessary changes.

**Comment by yssambare12** [comment]
> @yssambare12 code analysis failed, please check. also add changelog for this.

All check's are passed now, please have a look.

**Comment by yssambare12** [comment]
> @yssambare12 code analysis failed, please check. also add changelog for this.

All checks are passed now, please have a look.

**Review by imnavanath — APPROVED** [review]

**Pull request merged**
