### PR TITLE
AST-1728 - Optimization & improvement in UI of Astra meta settings

### PR DESCRIPTION
**Pull request by imnavanath**
### Description
- Tasks under this story will cover in this PR -
- https://wp-astra.atlassian.net/browse/AST-1728

### Types of changes
- New features

### How has this been tested?
- Check new updated UI of Astra meta settings & check backward in necessary cases

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

### CODE REVIEW

**Comment by premanshup** [comment]
@imnavanath Code analysis and E2E checks are failing, please check.

**Comment by imnavanath** [comment]
> @imnavanath Code analysis and E2E checks are failing, please check.

@GauravKhupse / @bsfsnehal can you help please here.

**Comment by bsfsnehal** [comment]
> 



> > @imnavanath Code analysis and E2E checks are failing, please check.
> 
> @GauravKhupse / @bsfsnehal can you help please here.

checking

**Comment by imnavanath** [comment]
Same fails here as well @GauravKhupse, @bsfsnehal - https://github.com/brainstormforce/astra/pull/4250

**Comment by bsfsnehal** [comment]
> Same fails here as well @GauravKhupse, @bsfsnehal - #4250

checking

**Comment by imnavanath** [comment]
@premanshup Disable Title meta option E2E PR is failing, it will surely fail because we removed the toggle and moved to eye trigger = https://share.bsf.io/lluEp5Y2 @GauravKhupse, @bsfsnehal is reverting that PR. 

Then for offcanvas there are some issues it will also reverting. So till then can we merge this PR as this is blocker for preparing package.

**Comment by premanshup** [comment]
Okay @imnavanath

**Pull request merged**
