### PR TITLE
AST-526 - refactor: As version_compare fails in beta release comparison added function for it

### PR DESCRIPTION
**Pull request by imnavanath**
### Description
- Version_compare function fails for beta-version comparison
- Added function for it using preg_replace

### Types of changes
- Bug fix 

### How has this been tested?
- With any comparison case which we added for beta version check
- Ex: Title, Tagline colors not appearing 
- Task - https://wp-astra.atlassian.net/browse/AST-526

### Checklist:
- [x] My code is tested
- [x] My code passes the PHPCS tests
- [x] My code follows accessibility standards 
- [x] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [x] I've included developer documentation 
- [x] I've added proper labels to this pull request

### CODE REVIEW

**Comment by sagarb90** [comment]
@imnavanath [Here ](https://github.com/brainstormforce/astra/blob/05b57d89062589c0fc0345383ca7f257d2462e55/inc/customizer/configurations/layout/class-astra-site-identity-configs.php#L314)is remaining to change the same .

**Comment by imnavanath** [comment]
> @imnavanath [Here ](https://github.com/brainstormforce/astra/blob/05b57d89062589c0fc0345383ca7f257d2462e55/inc/customizer/configurations/layout/class-astra-site-identity-configs.php#L314)is remaining to change the same .

@sagarb90 this is changed already, https://share.bsf.io/E0uA76eW do you mean somewhere else is missing?

**Comment by sagarb90** [comment]
> > @imnavanath [Here ](https://github.com/brainstormforce/astra/blob/05b57d89062589c0fc0345383ca7f257d2462e55/inc/customizer/configurations/layout/class-astra-site-identity-configs.php#L314)is remaining to change the same .
> 
> @sagarb90 this is changed already, https://share.bsf.io/E0uA76eW do you mean somewhere else is missing?

Yes Missing in this file and line no.-  `/inc/customizer/configurations/layout/class-astra-site-identity-configs.php#L314`

**Comment by imnavanath** [comment]
> > > @imnavanath [Here ](https://github.com/brainstormforce/astra/blob/05b57d89062589c0fc0345383ca7f257d2462e55/inc/customizer/configurations/layout/class-astra-site-identity-configs.php#L314)is remaining to change the same .
> > 
> > 
> > @sagarb90 this is changed already, https://share.bsf.io/E0uA76eW do you mean somewhere else is missing?
> 
> @imnavanath Yes Missing in this file and line no.- `/inc/customizer/configurations/layout/class-astra-site-identity-configs.php#L314`

Yes in the same file it's done - https://share.bsf.io/2NuqRkD7

**Review by sagarb90 — APPROVED** [review]

**Review by abhishek-bsf — APPROVED** [review]

**Review by premanshup — APPROVED** [review]

**Pull request merged**
