### PR TITLE
AST-956 - Modified theme and link color with sufficient contrast ratio

### PR DESCRIPTION
**Pull request by patilvikasj**
### Description
Link color and theme color code modified according to contrast ratio. This is regression of #2768. 

This should fix the tests that caught this regression - https://github.com/brainstormforce/astra/pull/2881#issuecomment-922878143

### Checklist:
- [x] My code is tested
- [x] My code passes the PHPCS tests
- [x] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

### CODE REVIEW

**Comment by imnavanath** [comment]
This don't need backwards, right @patilvikasj ?

**Comment by patilvikasj** [comment]
> This don't need backwards, right @patilvikasj ?

@imnavanath Yes. It does not need to maintain Backward compatibility as color change is not noticeable.

**Review by imnavanath — APPROVED** [review]

**Comment by Nikschavan** [comment]
@patilvikasj It is always recommended to link to the previous issues/PRs etc. document as much information possible so that it gets easier to find it in the future.

**Comment by Nikschavan** [comment]
> @patilvikasj It is always recommended to link to the previous issues/PRs etc. document as much information possible so that it gets easier to find it in the future.

I was a bit quick to comment this, I missed the link in the description above. I updated the link to mention the PR instead of hyperlink to a word. Also mentioned the PR #2881.

**Review by Nikschavan — APPROVED** [review]

**Review by premanshup — APPROVED** [review]

**Pull request merged**
