### PR TITLE
AST-268 - Color picker tooltip appear on hover of selection area & it's palette

### PR DESCRIPTION
**Pull request by imnavanath**
### Description
- On hover of color picker popover the tooltip of that color is visible.
- Ideally only on that color button hover it should appear, not on the entire popover.

### Screenshots
- https://a.cl.ly/04uArGBL

### Types of changes
- Bug fix

### How has this been tested?
- Check any color picker
- Issue was specifically to color group control, because we added tooltip over there only

### Checklist:
- [x] My code is tested
- [x] My code passes the PHPCS tests
- [x] My code follows accessibility standards 
- [x] I've included any necessary tests 
- [x] I've included developer documentation 
- [x] I've added proper labels to this pull request

### CODE REVIEW

**Review by premanshup — APPROVED** [review]

**Comment by premanshup** [comment]
@imnavanath Do check why the GitHub check is failing.

**Comment by imnavanath** [comment]
> @imnavanath Do check why the GitHub check is failing.

@premanshup I think this PR needs to be merge - https://github.com/brainstormforce/astra/pull/3263

**Comment by premanshup** [comment]
> > @imnavanath Do check why the GitHub check is failing.
> 
> @premanshup I think this PR needs to be merge - #3263
> Compressed Size: is failing.

Can you please confirm if this is working in this PR #3263

**Comment by imnavanath** [comment]
> Can you please confirm if this is working in this PR #3263

Facing same problem there also - https://github.com/brainstormforce/astra/pull/3263/checks?check_run_id=3610486150

**Pull request merged**
