### PR TITLE
Revert "Revert "AST-659 - fix: Default text for add widget is align in top.""

### PR DESCRIPTION
**Pull request by premanshup**
Reverts brainstormforce/astra#3182

### CODE REVIEW

**Comment by imnavanath** [comment]
@premanshup I think we can merge this PR first before this PR = https://github.com/brainstormforce/astra/pull/3184

**Comment by premanshup** [comment]
> @premanshup I think we need to merge this PR first before this PR = #3184

Okay, I will merge this once `next-release` is merged in `release-candidate` - https://github.com/brainstormforce/astra/pull/3161

@imnavanath  So I think this fix needs to go along with the Gutenberg editor changes as well?

**Comment by imnavanath** [comment]
> @imnavanath So I think this fix needs to go along with the Gutenberg editor changes as well?

Yes correct @premanshup

**Comment by imnavanath** [comment]
As 0 comparison, closing this PR.

**Pull request closed without merging**
