### PR TITLE
Copyright color

### PR DESCRIPTION
**Pull request by SimranChougule1**
### Description

Test case for copyright color

### How has this been tested?

npm run test:e2e:interactive tests/e2e/specs/customizer/Copyright/copyright-color.test.js

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

### CODE REVIEW

**Comment by Swapnildhanrale** [comment]
@SimranChougule1 need to resolve the conflicts

**Comment by premanshup** [comment]
@SimranChougule1 Please check why the package-lock.json file is delete?
cc: @sushmak02

**Comment by premanshup** [comment]
@SimranChougule1 / @sushmak02 Please mention task ID in all the PR titles as well.

**Comment by SimranChougule1** [comment]
Okay @premanshup

**Comment by SimranChougule1** [comment]
closing this PR because of deleted package-lock.json file, created new one

**Pull request closed without merging**
