### PR TITLE
AST-502 - Improve accessibility - always show aria-label attribute on builder social icons

### PR DESCRIPTION
**Pull request by tristanmason**
### Description
Currently, the Header Builder social icons only show aria-label attribute if "Show Label" switch is ON in the customizer. But the ARIA label is actually needed more when "Show Label" is off. To improve accessibility, instead of using the Show Label switch as the conditional, always show the aria-label attribute. If the user provides a Label in the customizer, use that for the aria-label. If not, use the icon name as the aria-label.

### Screenshots
https://imgur.com/a/TtIhcNm

### Types of changes

In class-astra-builder-ui-controller.php, check for $item['label'] instead of $show_label. If $item['label'] has a value, use that. If not, show the icon name $item['id'] as the default aria-label, so there is always an appropriate aria-label for the icon.

### How has this been tested?
Tested in local development env by examining the header builder social icons aria-label attributes with different customizer settings, different labels, no label.

### Checklist:
- [ ] My code is tested
- [ ] My code passes the PHPCS tests
- [ ] My code follows accessibility standards 
- [ ] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [ ] I've added proper labels to this pull request

### CODE REVIEW

**Review by imnavanath — APPROVED** [review]

**Review by sagarb90 — APPROVED** [review]

**Comment by tristanmason** [comment]
I'm just beginning to learn your process and branches, so I'm not sure why so many other commits appeared with this pull request... I was trying to submit [this one](https://github.com/brainstormforce/astra/pull/2770/commits/b8413c6c26012e131b8daa1065b21ecadc264119). Anyway, please let me know if you need me to do something differently. Thanks!

**Comment by premanshup** [comment]
@tristanmason Thank you for this PR. Actually the PR was not updated with the latest code which is why you were seeing other changes too. I have updated the latest code and now the changes are looking good.
I have added this PR for testing. Once tested, it will be released in the upcoming version of theme `v2.5.0`

**Review by premanshup — APPROVED** [review]

**Review by abhishek-bsf — APPROVED** [review]

**Comment by premanshup** [comment]
@tristanmason Thank you for the PR. This is merged and will be released in `v2.5.0` 👍🏼

**Comment by tristanmason** [comment]
@premanshup Great, thank you!

**Pull request merged**
