### PR TITLE
AST-780 - Enable axe tests after e2e tests

### PR DESCRIPTION
**Pull request by Nikschavan**
### Description
Run accessibility tests after each e2e tests.

Uses [jest-puppeteer-axe](https://www.npmjs.com/package/@wordpress/jest-puppeteer-axe) tests on frontend after each e2e test.

### Types of changes

New feature (non-breaking change which adds functionality)

### Checklist:
- [x] My code is tested
- [x] My code passes the PHPCS tests
- [x] My code follows accessibility standards 
- [x] My code has proper inline documentation 
- [ ] I've included any necessary tests 
- [ ] I've included developer documentation 
- [x] I've added proper labels to this pull request

### CODE REVIEW

**Review by imnavanath — APPROVED** [review]

**Comment by Nikschavan** [comment]
@shubhw12 After #3189 Can you merge that to this PR as well?

Let's get this PR merged after #3189 so that we have axe-tests running on each e2e test.

**Comment by imnavanath** [comment]
@Nikschavan this AXE testing failing, can you help here.

**Comment by Nikschavan** [comment]
@imnavanath These are actual accessibility errors being reported, can you check where these are coming from?

I am guessing some new tests were added which are enabling new layouts, which are auto-tested?

**Comment by Nikschavan** [comment]
This error is related to AST-272, This was fixed in #2768, but after global color palette fix this seems to have broken again.

@patilvikasj Can you check this?

**Comment by Nikschavan** [comment]
The broken test is fixed in #3309

**Review by premanshup — APPROVED** [review]

**Pull request merged**
